version: "3"

services:
   backend:
      build: ./php
   frontend:
      build: ./
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./production.conf:/etc/nginx/conf.d/default.conf
         - ./:/usr/share/nginx/html
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/brandonhuffman.dev/fullchain.pem:/etc/letsencrypt/live/brandonhuffman.dev/fullchain.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/brandonhuffman.dev/privkey.pem:/etc/letsencrypt/live/brandonhuffman.dev/privkey.pem
